[package]
name = "hash_forge"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.1"
clap = { version = "4.5.47", features = ["derive"] }
md2 = "0.10.2"
md4 = "0.10.2"
md5 = "0.8.0"
md6 = "2.0.3"
sha1 = "0.10.6"
sha2 = "0.10.9"
sha3 = "0.10.8"
